-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 18:54:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MyBankDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MyBankDB` ;

-- -----------------------------------------------------
-- Schema MyBankDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyBankDB` DEFAULT CHARACTER SET utf8 ;
USE `MyBankDB` ;

-- -----------------------------------------------------
-- Table `MyBankDB`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyBankDB`.`cities` ;

CREATE TABLE IF NOT EXISTS `MyBankDB`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MyBankDB`.`cities` (`name` ASC);


-- -----------------------------------------------------
-- Table `MyBankDB`.`martial_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyBankDB`.`martial_status` ;

CREATE TABLE IF NOT EXISTS `MyBankDB`.`martial_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MyBankDB`.`martial_status` (`name` ASC);


-- -----------------------------------------------------
-- Table `MyBankDB`.`nationality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyBankDB`.`nationality` ;

CREATE TABLE IF NOT EXISTS `MyBankDB`.`nationality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MyBankDB`.`nationality` (`name` ASC);


-- -----------------------------------------------------
-- Table `MyBankDB`.`disability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyBankDB`.`disability` ;

CREATE TABLE IF NOT EXISTS `MyBankDB`.`disability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `MyBankDB`.`disability` (`name` ASC);


-- -----------------------------------------------------
-- Table `MyBankDB`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyBankDB`.`clients` ;

CREATE TABLE IF NOT EXISTS `MyBankDB`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `birthday_date` DATE NOT NULL,
  `passport_series` VARCHAR(45) NOT NULL,
  `passport_number` VARCHAR(45) NOT NULL,
  `passport_authority` VARCHAR(45) NOT NULL,
  `passport_issue_date` DATE NOT NULL,
  `passport_identification_number` VARCHAR(45) NOT NULL,
  `birthday_place` VARCHAR(45) NOT NULL,
  `actual_residential_city_id` INT NOT NULL,
  `actual_address` VARCHAR(45) NOT NULL,
  `home_phone_number` VARCHAR(45) NULL,
  `cellular_phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `place_of_work` VARCHAR(45) NULL,
  `job_title` VARCHAR(45) NULL,
  `residential_address` VARCHAR(45) NOT NULL,
  `martial_status_id` INT NOT NULL,
  `nationality_id` INT NOT NULL,
  `disability_id` INT NOT NULL,
  `is_retired` TINYINT(1) NOT NULL,
  `monthly_income` DECIMAL(45, 2) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clients_cities1`
    FOREIGN KEY (`actual_residential_city_id`)
    REFERENCES `MyBankDB`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_martial_status1`
    FOREIGN KEY (`martial_status_id`)
    REFERENCES `MyBankDB`.`martial_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_nationality1`
    FOREIGN KEY (`nationality_id`)
    REFERENCES `MyBankDB`.`nationality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_disability1`
    FOREIGN KEY (`disability_id`)
    REFERENCES `MyBankDB`.`disability` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clients_cities1_idx` ON `MyBankDB`.`clients` (`actual_residential_city_id` ASC);

CREATE INDEX `fk_clients_martial_status1_idx` ON `MyBankDB`.`clients` (`martial_status_id` ASC);

CREATE INDEX `fk_clients_nationality1_idx` ON `MyBankDB`.`clients` (`nationality_id` ASC);

CREATE INDEX `fk_clients_disability1_idx` ON `MyBankDB`.`clients` (`disability_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `MyBankDB`.`cities`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyBankDB`;
INSERT INTO `MyBankDB`.`cities` (`id`, `name`) VALUES (DEFAULT, 'Минск');
INSERT INTO `MyBankDB`.`cities` (`id`, `name`) VALUES (DEFAULT, 'Гомель');
INSERT INTO `MyBankDB`.`cities` (`id`, `name`) VALUES (DEFAULT, 'Гродно');
INSERT INTO `MyBankDB`.`cities` (`id`, `name`) VALUES (DEFAULT, 'Брест');
INSERT INTO `MyBankDB`.`cities` (`id`, `name`) VALUES (DEFAULT, 'Витебск');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyBankDB`.`martial_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyBankDB`;
INSERT INTO `MyBankDB`.`martial_status` (`id`, `name`) VALUES (DEFAULT, 'Не замужем \\ холост');
INSERT INTO `MyBankDB`.`martial_status` (`id`, `name`) VALUES (DEFAULT, 'Замужем \\ женат');
INSERT INTO `MyBankDB`.`martial_status` (`id`, `name`) VALUES (DEFAULT, 'Разведен (-а)');
INSERT INTO `MyBankDB`.`martial_status` (`id`, `name`) VALUES (DEFAULT, 'Вдовец \\ Вдова');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyBankDB`.`nationality`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyBankDB`;
INSERT INTO `MyBankDB`.`nationality` (`id`, `name`) VALUES (DEFAULT, 'Белорус');
INSERT INTO `MyBankDB`.`nationality` (`id`, `name`) VALUES (DEFAULT, 'Русский');
INSERT INTO `MyBankDB`.`nationality` (`id`, `name`) VALUES (DEFAULT, 'Американец');
INSERT INTO `MyBankDB`.`nationality` (`id`, `name`) VALUES (DEFAULT, 'Украинец');
INSERT INTO `MyBankDB`.`nationality` (`id`, `name`) VALUES (DEFAULT, 'Литовец');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyBankDB`.`disability`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyBankDB`;
INSERT INTO `MyBankDB`.`disability` (`id`, `name`) VALUES (DEFAULT, 'Отсутствует');
INSERT INTO `MyBankDB`.`disability` (`id`, `name`) VALUES (DEFAULT, 'I группа');
INSERT INTO `MyBankDB`.`disability` (`id`, `name`) VALUES (DEFAULT, 'II группа');
INSERT INTO `MyBankDB`.`disability` (`id`, `name`) VALUES (DEFAULT, 'III группа');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyBankDB`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyBankDB`;
INSERT INTO `MyBankDB`.`clients` (`id`, `first_name`, `last_name`, `middle_name`, `birthday_date`, `passport_series`, `passport_number`, `passport_authority`, `passport_issue_date`, `passport_identification_number`, `birthday_place`, `actual_residential_city_id`, `actual_address`, `home_phone_number`, `cellular_phone_number`, `email`, `place_of_work`, `job_title`, `residential_address`, `martial_status_id`, `nationality_id`, `disability_id`, `is_retired`, `monthly_income`) VALUES (DEFAULT, 'Василий', 'Пупкин', 'Федорович', '1980-04-13', 'MP', '1236547', 'РУВД', '2005-04-13', '7123456А001РВ3', 'город', 1, 'ул. Котовского', '+375171234569', '+375441234567', 'vasya@mail.com', 'завод', 'рабочий', 'город', 2, 3, 1, false, 100.0);
INSERT INTO `MyBankDB`.`clients` (`id`, `first_name`, `last_name`, `middle_name`, `birthday_date`, `passport_series`, `passport_number`, `passport_authority`, `passport_issue_date`, `passport_identification_number`, `birthday_place`, `actual_residential_city_id`, `actual_address`, `home_phone_number`, `cellular_phone_number`, `email`, `place_of_work`, `job_title`, `residential_address`, `martial_status_id`, `nationality_id`, `disability_id`, `is_retired`) VALUES (DEFAULT, 'Федор', 'Сидоров', 'Иванович', '1990-04-13', 'MP', '1236547', 'РУВД', '2005-04-13', '7123456А001РВ3', 'город', 1, 'ул. Котовского', '', '', '', '', '', 'город', 3, 2, 2, false);
INSERT INTO `MyBankDB`.`clients` (`id`, `first_name`, `last_name`, `middle_name`, `birthday_date`, `passport_series`, `passport_number`, `passport_authority`, `passport_issue_date`, `passport_identification_number`, `birthday_place`, `actual_residential_city_id`, `actual_address`, `home_phone_number`, `cellular_phone_number`, `email`, `place_of_work`, `job_title`, `residential_address`, `martial_status_id`, `nationality_id`, `disability_id`, `is_retired`) VALUES (DEFAULT, 'Илья', 'Ктотиков', 'Игоревич', '1975-04-13', 'MP', '9654321', 'РУВД', '2005-04-13', '7123456А001РВ3', 'город', 1, 'ул. Котовского', '', '', 'some@email.com', '', '', 'город', 4, 1, 3, true);

COMMIT;

